[slack]
token = "xxxx-xxxxxxx"
channel = "tidb-ddl-team"
user = "github_reporter"

[jira]
user = "user"
password  = "password"
endpoint = "https://url.com/jira/"
server-id = "xxxx"
server = "PingCAP JIRA"
project = "TiDB"
oncall = "OnCall"

[confluence]
user = "user"
password  = "password"
endpoint = "https://url.com/confluence/"
space = "TT"
weekly-path = "Weekly Reports"

[github]
token = "xxx-xxxxx"
repos = [
    "pingcap/tidb",
]

[[teams]]
name = "Team"

    [[teams.members]]
    name = "Wink Yao"
    github = "winkyao"
    email = "wink@pingcap.com"